"""add users

Revision ID: 378debe6f999
Revises: 641dcd726a10
Create Date: 2025-07-07 23:01:44.420037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "378debe6f999"
down_revision: Union[str, None] = "641dcd726a10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "id",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "password", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("id_pkey")),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
