"""add users3

Revision ID: c39f58cee34d
Revises: 378debe6f999
Create Date: 2025-07-07 23:05:16.685279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c39f58cee34d"
down_revision: Union[str, None] = "378debe6f999"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=100), nullable=False))
    op.add_column(
        "users", sa.Column("firstname", sa.String(length=100), nullable=False)
    )
    op.add_column("users", sa.Column("lastname", sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "lastname")
    op.drop_column("users", "firstname")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
